# Generated by Django 3.2.7 on 2021-10-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titleG', models.CharField(max_length=200)),
                ('brandIdG', models.IntegerField(max_length=10)),
                ('usernameG', models.CharField(max_length=300)),
                ('isGuestG', models.BooleanField()),
                ('selectedCenterG', models.CharField(max_length=200)),
            ],
        ),
    ]
