# Generated by Django 3.2.7 on 2021-10-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPO_CUSTOM_LS_LIB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brandIdG',
            field=models.IntegerField(),
        ),
    ]
