# Generated by Django 3.2.7 on 2021-10-06 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GPO_CUSTOM_LS_LIB', '0002_alter_user_brandidg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='brandIdG',
        ),
        migrations.RemoveField(
            model_name='user',
            name='isGuestG',
        ),
        migrations.RemoveField(
            model_name='user',
            name='usernameG',
        ),
    ]
