# Generated by Django 3.2.7 on 2021-10-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPO_CUSTOM_LS_LIB', '0003_auto_20211006_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='brandIdG',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='isGuestG',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usernameG',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
