# Generated by Django 3.2.7 on 2021-10-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPO_CUSTOM_LS_LIB', '0004_auto_20211006_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='brandIdG',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='isGuestG',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='titleG',
            field=models.CharField(default='Demo Live', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='usernameG',
            field=models.CharField(default='Guest', max_length=300),
        ),
    ]
