# Generated by Django 3.2.8 on 2021-10-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GPO_CUSTOM_LS_LIB', '0005_auto_20211007_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='titleG',
            field=models.CharField(default='', max_length=200),
        ),
    ]
